Console.WriteLine("Find max ");
int a;
Console.Write("Number a = ");
a = Convert.ToInt32(Console.ReadLine());
int b;
Console.Write("Number b = ");
b = Convert.ToInt32(Console.ReadLine());
int c;
Console.Write("Number c = ");
c = Convert.ToInt32(Console.ReadLine());
int max = a;
if (a > max) max = a;
if (b > max) max = b;
if (c > max) max = c;
Console.Write("max = ");
Console.WriteLine(max);